### PR TITLE
alert status works correcttly

### LINKED ISSUE #402: Alert status doesn't updating on Alerts page
**Describe the bug**
After resolving of alert on data entity page (Entity Alerts tab) his status doesn't updating on Alerts page.

**Set up**
odd-platform v0.3.2

**Steps to Reproduce**

1. Go to the object page, Notification tab;
2. Allow notification;
3. Go to the notification page;
4. Alerts count has been updated, but in the list we see resolved alert with the "Open" status.

**Expected behavior**
Right updating alerts statuses.

### PR DESCRIPTION
**Pull request by alinamiryuk**
- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing applications:)

**What changes did you make?** (Give an overview)
Alert status updating on Alerts page fixed

**Is there anything you'd like reviewers to focus on?**
Resolve #402 

**How Has This Been Tested?** (put an "X" next to an item)

- [X] Manually(please, describe, when necessary)

**Checklist** (put an "X" next to an item, otherwise PR will fail)
- [X] I have performed a self-review of my own code

Check out [Contributing](https://github.com/opendatadiscovery/odd-platform/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/opendatadiscovery/odd-platform/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

File: odd-platform-ui/src/components/Alerts/Alerts.tsx [hunk 1]
```diff
@@ -41,6 +41,10 @@ const Alerts: React.FC<AlertsProps> = ({
 }) => {
   React.useEffect(() => {
     fetchAlertsTotals();
+    fetchAllAlertList({
+      page: 1,
+      size: 30,
+    });
```
Comment (Leshe4ka) [inline odd-platform-ui/src/components/Alerts/Alerts.tsx:47]: I think it would be better to place fetching of all alerts in the AlertsList component, where we pass the method to fetch. Also, due to the fact that we have pagination on the alerts page, it is better to tie through it.

**Review by Leshe4ka — CHANGES_REQUESTED** [review]
Also, could you please check updating of open alerts count? It doesn't updates when you resolve alert in data entity alerts tab.

**Review by Leshe4ka — APPROVED** [review]

File: odd-platform-ui/src/components/Alerts/Alerts.tsx (hunk 1 above)
Comment (alinamiryuk) [reply odd-platform-ui/src/components/Alerts/Alerts.tsx]: done

File: odd-platform-ui/src/components/Alerts/AlertsList/AlertsList.tsx [hunk 2]
```diff
@@ -47,6 +47,13 @@ const AlertsList: React.FC<AlertsListProps> = ({
     fetchNextPage();
   }, [fetchAlerts]);
```
Comment (Leshe4ka) [inline odd-platform-ui/src/components/Alerts/AlertsList/AlertsList.tsx:48]: Could you also remove old useEffect? It turns out that we duplicated requests.

Comment (alinamiryuk) [reply odd-platform-ui/src/components/Alerts/AlertsList/AlertsList.tsx]: done
